# Generated by Django 5.0.6 on 2024-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
    ]
