# Generated by Django 5.0.6 on 2024-05-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='qualification',
        ),
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Faculty of science', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='FacultyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('faculty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_faculty', to='faculty.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_faculty', to='faculty.facultyhead'),
        ),
    ]
