# Generated by Django 5.0.6 on 2024-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('faculty', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='courses',
            field=models.ManyToManyField(related_name='faculty', to='courses.course'),
        ),
    ]
