from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()
class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=10, unique=True) #autogenerated
    courses = models.ManyToManyField('courses.Course', related_name="students")
    
    def save(self, *args, **kwargs):
        if not self.student_id:
            self.student_id = self.generate_student_id()
        super(StudentProfile, self).save(*args, **kwargs)

    def generate_student_id(self):
        last_student = StudentProfile.objects.all().order_by('id').last()
        if not last_student:
            return 'S0001'
        student_id = last_student.student_id
        student_int = int(student_id.split('S')[-1])
        new_student_int = student_int + 1
        new_student_id = 'S' + str(new_student_int).zfill(4)
        return new_student_id
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
