# Generated by Django 5.0.6 on 2024-05-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmental_head', to='faculty.faculty'),
        ),
    ]
